language: python
python:
  - "3.7-dev"
install:
  - pip install wheel six pytest
  - pip install numpy scipy
  - pip install scikit-image>=0.14.0
script:
  - python -m pytest
branches:
  only:
    - master
